### PR TITLE
Update hapi and node-sass so that hapi-sass works on node v4.0.0

### PR DESCRIPTION
**Pull request by edimoldovan**

### CODE REVIEW

**Comment by mdarnall** [comment]
Cool! I'll give this a quick test out locally. I'm guessing this should mean hapi-sass @2.0.0 with these changes.

**Comment by edimoldovan** [comment]
I agree. 2.0 is a good idea.

**Comment by edimoldovan** [comment]
@mdarnall Any chance to merging this soon?

**Comment by mdarnall** [comment]
Ya, sorry I should have time today, just reading about Hapi 10

**Comment by mdarnall** [comment]
So this didn't turn out to be as simple as updating the package.json. So I've started a new branch that's almost ready at #6 based on this PR and I'll close this one out. 

node-sass 1.0.0 targeted a pretty old version of Hapi, so I've updated it to match the newer server/plugin api. 

Looks like the last thing to do is to update the use of the node-sass api, which I should be able to do tomorrow.

**Comment by mdarnall** [comment]
FYI, #6 was merged and `v2.0.0` published to npm 

:beer: cheers!

**Pull request closed without merging**
