### PR TITLE
4.0.0 - Support for Hapi v17

### PR DESCRIPTION
**Pull request by emanuelet**

### CODE REVIEW

**Comment by patrickkettner** [comment]
@mdarnall any chance this could be merged?

**Comment by emanuelet** [comment]
regarding the support for older versions of Hapi I'm not super sure, but I will bump it to version 4 for safety anyway

**Comment by mdarnall** [comment]
Hi, looking at this now :)

**Comment by mdarnall** [comment]
Thanks for doing this. I'm going to use most of your changes and tweak a couple things there were issues with and open this as a 4.0.0 branch. 

Thanks again!

**Pull request closed without merging**
